#../sources/aq_axi_djpeg_ctrl.v
#../sources/aq_axi_djpeg.v
#../sources/aq_axi_lite_slave.v
../sources/aq_djpeg_regdata.v
../sources/aq_djpeg_ziguzagu.v
../sources/aq_djpeg_dqt.v
../sources/aq_djpeg_dht.v
../sources/aq_djpeg_hm_decode.v
../sources/aq_djpeg_huffman.v
../sources/aq_djpeg_idctb.v
../sources/aq_djpeg_idct_calc.v
../sources/aq_djpeg_idct.v
../sources/aq_djpeg_ycbcr_mem.v
../sources/aq_djpeg_ycbcr2rgb.v
../sources/aq_djpeg_ycbcr.v
../sources/aq_djpeg_fsm.v
../sources/aq_djpeg.v
./tb_aq_djpeg.v
